language: java

script:
 - ant;
 - ant test;

sudo: required

services:
  - docker
  
  
before_install:
- docker build FloraJuliane/green .
- docker run -d -p 127.0.0.1:80:4567 FloraJuliane/green /bin/sh -c "cd /root/green; bundle exec foreman start;"
- docker ps -a
- docker run FloraJuliane/green/bin/sh -c "cd /root/green; bundle exec rake test"