language: java

script:
 - ant;
 - ant test;


sudo: required

services:
  - docker
  
  
before_install:
- docker build -t green .
- docker run -d -p 127.0.0.1:80:4567 green /bin/sh -c " ant;"
- docker ps -a
- docker run floraJuliane/green/bin/sh -c "ant test"